baseURL = "https://chrisalbon.com/"
languageCode = "en-us"
title = "Chris Albon"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS"]
  section = ["RSS"]

# Allows raw HTML to render in markdown content files.
# Used to add linked images (i.e. flashcard images)
[markup.goldmark.renderer]
unsafe= true

[params]
  description = "Machine Learning Tutorials"
  images = ["images/frontpage_twitter_card.png"]
